Fix billing.require() onFailure error: add required onFailure callback
- Extract redirect from authenticate.admin() for use in onFailure callback
- Add onFailure callback to billing.require() that redirects to credits page on failure
- onFailure is required parameter for billing.require() in Remix
- This fixes 'options.onFailure is not a function' error